eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8762
  tomcat:
    uri-encoding: UTF-8
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: service-client
  datasource:
    url: jdbc:mysql://localhost/mysql?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo spring.cloud.config.label=master
          username: ws678
          password: 678678678w
  data:
    mongodb:
      uri: mongodb://192.168.31.130:27017/1804b
  redis:
    database: 0
    host: 192.168.31.130
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 3000
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml