spring:
  application:
    name: service-zuul
server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
zuul:
  routes:
    hhh:
      path: /feign/**
      serviceId: service-feign